import java.util.ArrayList;


/*Author: Suraj Sharma
 * ID: ss2261*/

public class transpositionCipherQ5 {



    public static void main(String[] args) {

      //  System.out.println("Decrypted as : "+ decryptTrans("SHADSUCIHUIHATSBLEERAEHIHEIDREDKSRHESLTHBYIDOTEANFCOTSWEOHIESWABREHHHERTOLFCAOZPBETHFRRSHIOIYTWGOSCBUVIEDEAYEOFNHAEAEREDZSSEMYYESCEIIRNETLTFTTRSUNTMAANRSHIHIDHSTWADEFCOETLIANESUYKAEILRUOYNCFHNOECAWOITTIREFAEAADEHREJEBNDOYTIEBEYIADWWIHHRGHAESENAYSVRDRTETDDNAAHDZEETELHDSORLSGEVWEOERFDFCEEPBRHOSIFADTIREOVDROONFOEZIIHHDINTENLIBWOEHSFEWEARCWZTILSAODSTDOGALAUTSEOIRSLRYEWRPNWANEEEOWNBEAGLYYEETNHWHPHHRNOOPPFMNEEIONELEEVEAVMLAOWRHXDELTIAONADIHSEDUEOLRUOOUTZDNOEDDOINGNVAHUBEOOSAONIACZBNDATRAASDYRTICSOEONLEHLSDSEPSTHSGRNEIHNEILWREOTAHEEHEAAOLDPWLLOYTVCTISDADTERSIETIROOAPUAEESTMGSSFEEPSLLWIELMRRAHTGRAEOWVSIOECERRSMRTRHITNAHUTTNHESWHOOEPTTTANITIGEEEEVLEIKASEWIDWAOCHOIESUHCERLIYSLUISPNEERMAIRWLISDFIRONTHHGWRMNENCQRTWEAOOIRAEHDANFEDOGILEUTSDNNWEAWWYKRLAOUHYDOBHINUROEDEHSWENUTOTOINTZSTRSDLGELRDNTAIHATITTAAVFAYHEHCOACHSFREHEIAAGORTIALDOVOTNIOYEO"));


    for(int x=4; x<=6; x++){

        decryptTrans("SHADSUCIHUIHATSBLEERAEHIHEIDREDKSRHESLTHBYIDOTEANFCOTSWEOHIESWABREHHHERTOLFCAOZPBETHFRRSHIOIYTWGOSCBUVIEDEAYEOFNHAEAEREDZSSEMYYESCEIIRNETLTFTTRSUNTMAANRSHIHIDHSTWADEFCOETLIANESUYKAEILRUOYNCFHNOECAWOITTIREFAEAADEHREJEBNDOYTIEBEYIADWWIHHRGHAESENAYSVRDRTETDDNAAHDZEETELHDSORLSGEVWEOERFDFCEEPBRHOSIFADTIREOVDROONFOEZIIHHDINTENLIBWOEHSFEWEARCWZTILSAODSTDOGALAUTSEOIRSLRYEWRPNWANEEEOWNBEAGLYYEETNHWHPHHRNOOPPFMNEEIONELEEVEAVMLAOWRHXDELTIAONADIHSEDUEOLRUOOUTZDNOEDDOINGNVAHUBEOOSAONIACZBNDATRAASDYRTICSOEONLEHLSDSEPSTHSGRNEIHNEILWREOTAHEEHEAAOLDPWLLOYTVCTISDADTERSIETIROOAPUAEESTMGSSFEEPSLLWIELMRRAHTGRAEOWVSIOECERRSMRTRHITNAHUTTNHESWHOOEPTTTANITIGEEEEVLEIKASEWIDWAOCHOIESUHCERLIYSLUISPNEERMAIRWLISDFIRONTHHGWRMNENCQRTWEAOOIRAEHDANFEDOGILEUTSDNNWEAWWYKRLAOUHYDOBHINUROEDEHSWENUTOTOINTZSTRSDLGELRDNTAIHATITTAAVFAYHEHCOACHSFREHEIAAGORTIALDOVOTNIOYEO",x);
    }
    }

    public static void decryptTrans(String cipher,int columns){
        ArrayList<String> bins = new ArrayList<>();// store the groups
        StringBuilder decryptedMessage = new StringBuilder(); //store the final message

        int rows = cipher.length()/columns;
        System.out.println();
        System.out.println("Breaking the cipher down into rows and columns:");
        System.out.println();
        System.out.println("Number of rows: "+rows);

        String result;

        //split into groups
        for(int i=0; i <rows; i++) {
            result="";
            for (int x =i; x < cipher.length(); x = x + rows) {
                result +=cipher.charAt(x);
            }
            bins.add(i,result);
        }

        for(int x=0; x<rows; x++) {

            System.out.println((x+1)+"   "+bins.get(x));
        }

        System.out.println();
        System.out.println();
    //append the message
        for(int x=0; x<rows; x++) {

            decryptedMessage.append(bins.get(x));

        }


        System.out.println("This reads as : "+ decryptedMessage.substring(0,30));
        System.out.println("With collumns defined as: "+ columns);

    }
}
