

/*Author: Suraj Sharma
 * ID: ss2261*/

public class vignereCipherQ4 {


    public static String mainKey = "QORD"; //key has a length of 4 letters //QORD



    public static void main(String[] args) {


       // System.out.println("Encrypted as: "+ encrpytVignere("NEATHITANDSHELIFTEDTHECANDLETO", mainKey).toString());
        System.out.println();
        System.out.println(vignereCipherQ3.findFrequencies("UBZHDQVDIKVOBOJPOVRSFWEHIGZIYVRYUOMHHMCDHUVIQFDHYHYHHSEJBWJKEFTRBCELQZPRKKZOBPVLDJROKOSOUOJDMWWHJCDHRSKWUFKKQBRZEARQEIKRVHYHBOIJUGKPQBJLEBZQJVVFEIEWHMJRFZVDISGOUOJHTSRUJSJVORZVQPLVUMFXHAZQTCWWXSWHUZZQWHYDJMFXMWCOIHRQTWEPOKRBRIKPOVZVJCIBYKRQJMFXJCBQEKZWOCLPKGKOUHDHJSCOOCLBEINLBZERJZZNUAVVEKVOBHVOBWKLVMFXMWJKJCUHQFVVJHYLIDIHSWFXIVZVJCIBJVVQOSJLMOJEEFEDJGFDDRJRQBERTCDLDWZZQGSRHBRWCOIOEHKVXSJDYRTDJQYLDURWXWJZEFUVQGRKUZGOYUYWBMRVJVVBMSIHIDFNUBRQTWXUUKLSJVVUUOEGYKRVYBKKUGZAJVJWQBUDHRNKUBZOUTKVSVFRBOEGJVVBIOZGYVRGWFVDJOGWDSJVQBUVXCLOTARNUOXRERKHQQYHHGFLJKRVISKWBSUWXOKLIVFXBRSHEBVEKHKKUFVZQGKUEISOUWEPOTRPYZPIQHYHHKRVDCKYUFPLDRLVJFZRKGRQTVVGHOENQZZWJZVBUGPHIDFRHQYLBRERJVZQWBVZXSGUUGJHTVVUCCIHSZFVUZPWEVZVIWUHQBUWXSEWXSIHYGJRCSKKYBXYUFPXDIJXQZREEIKLJOSRKHDHYWNDIHVVIGSUUOKKGIZFASEHTMVVTSRUUGKQUJVUCWEGYWRPDCKDTIIEUMWLUZUEKHRGKFSHHJZOBSRGUGTH",4));
        System.out.println();
        System.out.println("Decrypted as: "+ decryptVignere("UBZHDQVDIKVOBOJPOVRSFWEHIGZIYVRYUOMHHMCDHUVIQFDHYHYHHSEJBWJKEFTRBCELQZPRKKZOBPVLDJROKOSOUOJDMWWHJCDHRSKWUFKKQBRZEARQEIKRVHYHBOIJUGKPQBJLEBZQJVVFEIEWHMJRFZVDISGOUOJHTSRUJSJVORZVQPLVUMFXHAZQTCWWXSWHUZZQWHYDJMFXMWCOIHRQTWEPOKRBRIKPOVZVJCIBYKRQJMFXJCBQEKZWOCLPKGKOUHDHJSCOOCLBEINLBZERJZZNUAVVEKVOBHVOBWKLVMFXMWJKJCUHQFVVJHYLIDIHSWFXIVZVJCIBJVVQOSJLMOJEEFEDJGFDDRJRQBERTCDLDWZZQGSRHBRWCOIOEHKVXSJDYRTDJQYLDURWXWJZEFUVQGRKUZGOYUYWBMRVJVVBMSIHIDFNUBRQTWXUUKLSJVVUUOEGYKRVYBKKUGZAJVJWQBUDHRNKUBZOUTKVSVFRBOEGJVVBIOZGYVRGWFVDJOGWDSJVQBUVXCLOTARNUOXRERKHQQYHHGFLJKRVISKWBSUWXOKLIVFXBRSHEBVEKHKKUFVZQGKUEISOUWEPOTRPYZPIQHYHHKRVDCKYUFPLDRLVJFZRKGRQTVVGHOENQZZWJZVBUGPHIDFRHQYLBRERJVZQWBVZXSGUUGJHTVVUCCIHSZFVUZPWEVZVIWUHQBUWXSEWXSIHYGJRCSKKYBXYUFPXDIJXQZREEIKLJOSRKHDHYWNDIHVVIGSUUOKKGIZFASEHTMVVTSRUUGKQUJVUCWEGYWRPDCKDTIIEUMWLUZUEKHRGKFSHHJZOBSRGUGTH", mainKey).toString().substring(0,30));
       String val =decryptVignere("UBZHDQVDIKVOBOJPOVRSFWEHIGZIYVRYUOMHHMCDHUVIQFDHYHYHHSEJBWJKEFTRBCELQZPRKKZOBPVLDJROKOSOUOJDMWWHJCDHRSKWUFKKQBRZEARQEIKRVHYHBOIJUGKPQBJLEBZQJVVFEIEWHMJRFZVDISGOUOJHTSRUJSJVORZVQPLVUMFXHAZQTCWWXSWHUZZQWHYDJMFXMWCOIHRQTWEPOKRBRIKPOVZVJCIBYKRQJMFXJCBQEKZWOCLPKGKOUHDHJSCOOCLBEINLBZERJZZNUAVVEKVOBHVOBWKLVMFXMWJKJCUHQFVVJHYLIDIHSWFXIVZVJCIBJVVQOSJLMOJEEFEDJGFDDRJRQBERTCDLDWZZQGSRHBRWCOIOEHKVXSJDYRTDJQYLDURWXWJZEFUVQGRKUZGOYUYWBMRVJVVBMSIHIDFNUBRQTWXUUKLSJVVUUOEGYKRVYBKKUGZAJVJWQBUDHRNKUBZOUTKVSVFRBOEGJVVBIOZGYVRGWFVDJOGWDSJVQBUVXCLOTARNUOXRERKHQQYHHGFLJKRVISKWBSUWXOKLIVFXBRSHEBVEKHKKUFVZQGKUEISOUWEPOTRPYZPIQHYHHKRVDCKYUFPLDRLVJFZRKGRQTVVGHOENQZZWJZVBUGPHIDFRHQYLBRERJVZQWBVZXSGUUGJHTVVUCCIHSZFVUZPWEVZVIWUHQBUWXSEWXSIHYGJRCSKKYBXYUFPXDIJXQZREEIKLJOSRKHDHYWNDIHVVIGSUUOKKGIZFASEHTMVVTSRUUGKQUJVUCWEGYWRPDCKDTIIEUMWLUZUEKHRGKFSHHJZOBSRGUGTH", mainKey).toString().substring(0,30);


        System.out.println();
        System.out.println();

        bruteForce();



    }

    
        /*Decryption method*/

        public static StringBuilder decryptVignere(String text, String decryptionKey){
            String cipherText = text;
            StringBuilder decryptedString = new StringBuilder();
            StringBuilder newDecryptedStringLength= new StringBuilder();


            //making the key the same length as String
            int y=0;
            for(int x=0;x<cipherText.length();x++) {
                if(y==decryptionKey.length()) {
                    y = 0;
                }
                if(cipherText.charAt(x)==' ') {
                    newDecryptedStringLength.append(" ");
                }
                else {
                    newDecryptedStringLength.append(decryptionKey.charAt(y++));
                }
            }

            for (int x =0; x< cipherText.length(); x++){


                char eachChar = (char) ((((cipherText.charAt(x) - newDecryptedStringLength.charAt(x))+26) % 26) + 'A');



                decryptedString.append(eachChar); //append each character

            }
            return decryptedString;
        }


        public static void bruteForce(){
            char[] key = mainKey.toCharArray();


            char c;

            for(c = 'A'; c <= 'Z'; ++c){
                key[2] = c; // i would change this for each letter
                mainKey = String.valueOf(key);
                System.out.println("Decrypted as: "+ decryptVignere("UBZHDQVDIKVOBOJPOVRSFWEHIGZIYVRYUOMHHMCDHUVIQFDHYHYHHSEJBWJKEFTRBCELQZPRKKZOBPVLDJROKOSOUOJDMWWHJCDHRSKWUFKKQBRZEARQEIKRVHYHBOIJUGKPQBJLEBZQJVVFEIEWHMJRFZVDISGOUOJHTSRUJSJVORZVQPLVUMFXHAZQTCWWXSWHUZZQWHYDJMFXMWCOIHRQTWEPOKRBRIKPOVZVJCIBYKRQJMFXJCBQEKZWOCLPKGKOUHDHJSCOOCLBEINLBZERJZZNUAVVEKVOBHVOBWKLVMFXMWJKJCUHQFVVJHYLIDIHSWFXIVZVJCIBJVVQOSJLMOJEEFEDJGFDDRJRQBERTCDLDWZZQGSRHBRWCOIOEHKVXSJDYRTDJQYLDURWXWJZEFUVQGRKUZGOYUYWBMRVJVVBMSIHIDFNUBRQTWXUUKLSJVVUUOEGYKRVYBKKUGZAJVJWQBUDHRNKUBZOUTKVSVFRBOEGJVVBIOZGYVRGWFVDJOGWDSJVQBUVXCLOTARNUOXRERKHQQYHHGFLJKRVISKWBSUWXOKLIVFXBRSHEBVEKHKKUFVZQGKUEISOUWEPOTRPYZPIQHYHHKRVDCKYUFPLDRLVJFZRKGRQTVVGHOENQZZWJZVBUGPHIDFRHQYLBRERJVZQWBVZXSGUUGJHTVVUCCIHSZFVUZPWEVZVIWUHQBUWXSEWXSIHYGJRCSKKYBXYUFPXDIJXQZREEIKLJOSRKHDHYWNDIHVVIGSUUOKKGIZFASEHTMVVTSRUUGKQUJVUCWEGYWRPDCKDTIIEUMWLUZUEKHRGKFSHHJZOBSRGUGTH", mainKey).toString().substring(0,30) + "       third key letter: "+ key[2]);
                System.out.println("Key value: "+mainKey);
                System.out.println();
                System.out.println();

            }








        }

    }









